name: CI
on:
  push:
    paths:
      - .github/workflows/build.yml
      - shell/**
      - .dockerignore
      - Dockerfile
  pull_request:
    paths:
      - .github/workflows/build.yml
      - shell/**
      - .dockerignore
      - Dockerfile

jobs:
  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2

      - name: Build final image
        run: docker build .

  publish:
    # needs: [verify]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=commit::$(git rev-parse --short HEAD)
          echo ::set-output name=build_date::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo ::set-output name=version::$TAG
            echo ::set-output name=platforms::linux/amd64
          elif [ "$BRANCH" = "master" ]; then
            echo ::set-output name=version::latest
            echo ::set-output name=platforms::linux/amd64
          else
            echo ::set-output name=version::$BRANCH
            echo ::set-output name=platforms::linux/amd64
          fi

      - name: Build and push scheme-basic image
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.build_date }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
            SCHEME=scheme-basic
          tags: qmcgaw/latexdevcontainer:${{ steps.vars.outputs.version }}
          push: true

      - name: Build and push scheme-full image
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.build_date }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
            SCHEME=scheme-full
          tags: qmcgaw/latexdevcontainer:${{ steps.vars.outputs.version }}-full
          push: true

      - if: github.event.ref == 'refs/heads/master'
        name: Microbadger hook
        run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/latexdevcontainer/xq5q57-42Lbxy5YlOvMG2gNnUD0=
        continue-on-error: true
